version: "3"

services:
  mosquitto:
    build:
      context: .
      dockerfile: ./docker/mosquitto.dockerfile
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config

  data-processor:
    build:
      context: .
      dockerfile: ./docker/python.dockerfile
    container_name: python
    depends_on:
      - mosquitto
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - TOPIC_1=${TOPIC_1}
    volumes:
      - .:/app/